Repository EduHaven/EduHaven, pull requests merged in 2025-09, with the labels that each got.

#587 Update README.md
  README.md
Labels: level 1, gssoc25

#533 NoteNest Improvements - Notes Feature
  Client/src/pages/NoteNest.jsx
Labels: level 3, gssoc25

#597 Add react-resizable-panels for adjustable chat layout
  Client/package-lock.json
  Client/package.json
  Client/src/pages/Chats.jsx
Labels: level 2, gssoc25

#599 🚀 Add Advanced Rate Limiting for Auth Routes
  Server/Middlewares/ratelimit.middleware.js
  Server/Routes/AuthRoutes.js
  Server/Tests/authRateLimiter.test.js
Labels: level 3, gssoc25

#605 Refactor imports to include file extensions and update dependencies for Argon2 and rate limiting
  Server/Controller/UserController.js
  Server/Routes/AuthRoutes.js
  Server/Routes/EventRoutes.js
  Server/Routes/NotesRoutes.js
  Server/Routes/StudySessionRoutes.js
  Server/Routes/ToDoRoutes.js
  Server/Routes/UserRoutes.js
  Server/package-lock.json
  Server/package.json
  Server/security/sanitizeMiddleware.js
  package.json
Labels: level 3, gssoc25

#607 Add helmet and hpp security middlewares
  Server/index.js
  Server/package-lock.json
  Server/package.json
  Server/security/securityMiddleware.js
Labels: level 3, gssoc25

#617 Remove Language Selector
  Client/.env.example
  Client/package-lock.json
  Client/src/App.jsx
  Client/src/components/settings/Sidebar.jsx
  Client/src/components/settings/TimeLanguage.jsx
Labels: level 2, gssoc25

#553 #494 issue fixed forgot password
  Client/src/App.jsx
  Client/src/Auth/ForgotPassword.jsx
  Client/src/Auth/Login.jsx
  Client/src/Auth/ResetPassword.jsx
  Client/src/Auth/SignUp.jsx
  Client/src/Auth/Signout.jsx
  Client/src/Auth/Verifyotp.jsx
  Client/src/components/stats/Badges.jsx
  Server/Controller/AuthController.js
  Server/Routes/AuthRoutes.js
  Server/utils/sendMail.js
Labels: level 3, gssoc25

#621 Fix: Show the default profile picture for suggested friends who don’t already have one. #614
  Client/package-lock.json
  Client/src/components/friendsSection/Avatar.jsx
  Client/src/components/friendsSection/FriendsRequests.jsx
  Client/src/components/friendsSection/SuggestedFriends.jsx
Labels: level 2, gssoc25

#630 Remove Skeleton from friend request section on session page #611
  Client/src/components/Avatar.jsx
  Client/src/components/friendsSection/FriendsRequests.jsx
  Client/src/components/friendsSection/SuggestedFriends.jsx
Labels: level 2, gssoc25

#634 remove unnecessary log from console
  Client/src/components/home/goals/GoalsComponent.jsx
  Client/src/components/home/navBar/Slogan.jsx
Labels: level 1, gssoc25

#635 Updated the checklist in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: level 1, gssoc25

#637 Added CI's for the pretier check , es lint and pr validation
  .github/workflows/eslint.yml
  .github/workflows/pr-validation.yml
  .github/workflows/prettier.yml
Labels: level 3, gssoc25

#638 Add automated comment on newly opened issues
  .github/workflows/issue-create-automate-message.yml
  .github/workflows/pr-validation.yml
Labels: level 2, gssoc25

#639 Refactoring friends
  Client/package-lock.json
  Client/package.json
  Client/src/App.jsx
  Client/src/api/friendApi.js
  Client/src/components/friendsPage/UserCard.jsx
  Client/src/components/friendsPage/tabs/AllFriends.jsx
  Client/src/components/friendsPage/tabs/FriendRequests.jsx
  Client/src/components/friendsPage/tabs/SentRequests.jsx
  Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
  Client/src/components/session/friendsSection/FriendsRequests.jsx
  Client/src/components/session/friendsSection/SentRequests.jsx
  Client/src/components/session/friendsSection/SuggestedFriends.jsx
  Client/src/components/settings/Friends.jsx
  Client/src/components/stats/ProfileCard/ProfileCard.jsx
  Client/src/queries/friendQueries.js
  Client/src/utils/errorHandler.js
Labels: level 3, gssoc25

#652 Refactored Notes.jsx
  Client/src/components/notes/NoteCard.jsx
  Client/src/components/notes/NoteEditor.jsx
  Client/src/components/notes/NoteHeader.jsx
  Client/src/components/notes/NotesList.jsx
  Client/src/components/notes/ToolbarButton.jsx
  Client/src/components/notes/note.css
  Client/src/pages/Notes.jsx
Labels: level 3, gssoc25

#668 Added Feedback Button on About Page
  Client/.env.example
  Client/src/pages/ProjectInfo.jsx
Labels: level 2, gssoc25

#669 update note styles and enhance Notes component reactivity
  Client/src/components/notes/note.css
  Client/src/index.css
  Client/src/pages/Notes.jsx
Labels: level 3, gssoc25

#671 Change your Password section have a link for better navigation
  Client/src/components/settings/Account.jsx
Labels: level 1, gssoc25

#672 Add ConfirmRemoveFriendModal component and integrate with Friends list
  Client/src/components/ConfirmRemoveFriendModal.jsx
  Client/src/components/settings/Friends.jsx
Labels: level 2, gssoc25

#688 Add cancel request button to UserCard and update friend request state management
  Client/src/components/friendsPage/UserCard.jsx
  Client/src/queries/friendQueries.js
Labels: level 2, gssoc25

#690 use morgan only on development
  Server/.env.example
  Server/index.js
  Server/package.json
Labels: level 2, gssoc25

#693 Fix the bullet points not showing in notes
  Client/src/components/notes/note.css
Labels: level 2, gssoc25

#692 Fix prettier and ESLint workflows
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  Client/eslint.config.js
  Client/public/sw.js
  Client/src/Auth/ForgotPassword.jsx
  Client/src/Auth/ResetPassword.jsx
  Client/src/Auth/SignUp.jsx
  Client/src/Auth/Signout.jsx
  Client/src/Auth/Verifyotp.jsx
  Client/src/components/Avatar.jsx
  Client/src/components/friendsPage/tabs/AllFriends.jsx
  Client/src/components/games/space-type/SpaceType.jsx
  Client/src/components/games/tic-tac-toe/TicTacToe.jsx
  Client/src/components/games/whac-a-mole/Whacamole.jsx
  Client/src/components/home/navBar/PinnedLinks.jsx
  Client/src/components/landingPage/HeroSection.jsx
  Client/src/components/landingPage/StudyRoom.jsx
  Client/src/components/session/friendsSection/SentRequests.jsx
  Client/src/components/session/friendsSection/SuggestedFriends.jsx
  Client/src/components/settings/Delete.jsx
  Client/src/components/skeletons/FriendsSkeletonLoader.jsx
  Client/src/components/skeletons/UserCardSkeleton.jsx
  Client/src/components/stats/Goals.jsx
  Client/src/components/stats/ProfileCard/ProfileCard.jsx
  Client/src/components/stats/Test.jsx
  Client/src/components/ui/button.jsx
  Client/src/hooks/WebRTC/UseMediaHandlers.jsx
  Client/src/pages/LandingPage.jsx
  Client/src/pages/PrivacyPolicy.jsx
  Client/src/pages/ProjectInfo.jsx
  Client/src/pages/Sessions.jsx
  Client/src/queries/friendQueries.js
  Server/Controller/AuthController.js
  Server/Controller/EventController.js
  Server/Controller/UserController.js
  Server/Database/Db.js
  Server/Middlewares/errorHandler.js
  Server/Middlewares/notFound.js
  Server/Routes/AuthRoutes.js
  Server/eslint.config.js
  Server/index.js
  Server/package-lock.json
  Server/package.json
  Server/utils/sendMail.js
Labels: level 3

#709 enhance deleteAccount functionality and update AuthRoutes for middleware
  Server/Controller/AuthController.js
  Server/Routes/AuthRoutes.js
Labels: level 3, gssoc25

#730 slogan hide
  Client/src/components/home/navBar/OnlineUsers.jsx
  Client/src/components/home/navBar/Slogan.jsx
Labels: level 1, gssoc25

#752 fix: update auto-comment script for issue creation
  .github/workflows/issue-create-automate-message.yml
Labels: level 2, gssoc25

#753 refactor: remove GSSoC Navigator product from AdCard component
  Client/public/navigator1.png
  Client/public/navigator2.png
  Client/src/components/AdCard.jsx
Labels: level 1, gssoc25

#755 improve-documentation-contributing
  CONTRIBUTING.md
Labels: level 1, gssoc25

#748 Fix theme color for horizontal line
  Client/src/components/about/AboutNav.jsx
  Client/src/components/notes/note.css
Labels: level 1, gssoc25

#757 fix(ui): align skeleton and friends page tabs layout with suggestions tab layout
  Client/src/components/friendsPage/MainContent.jsx
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/friendsPage/tabs/AllFriends.jsx
  Client/src/components/friendsPage/tabs/FriendRequests.jsx
  Client/src/components/friendsPage/tabs/SentRequests.jsx
  Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
  Client/src/components/skeletons/FriendsSkeletonLoader.jsx
  Client/src/components/skeletons/UserCardSkeleton.jsx
Labels: good first issue, level 2, gssoc25

#764 Fix: remove logo hover effect from about page
  Client/src/components/about/Hero.jsx
Labels: level 1, gssoc25

#759 Update README.md
  README.md
Labels: level 2, gssoc25

#790 Add active tab indicator and animation to NoteHeader and Notes page
  Client/src/components/notes/NoteHeader.jsx
  Client/src/pages/Notes.jsx
Labels: level 2, gssoc25

#792 Refactor EventController.js for better maintainability
  Server/Controller/EventController.js
Labels: bug, level 3, gssoc25

#799 fix insert image button and handle Cloudinary image removal
  Client/src/pages/Notes.jsx
  Server/Controller/NotesController.js
  Server/Routes/NotesRoutes.js
  Server/utils/Cloudnary.js
Labels: level 3, gssoc25

#798 Implemented full screen in notes card in home page
  Client/src/App.jsx
  Client/src/components/home/notes/BottomControls.jsx
  Client/src/components/notes/NoteEditor.jsx
  Client/src/pages/Notes.jsx
Labels: level 3, gssoc25

#803 Fix: sender name in mails
  Server/utils/sendMail.js
Labels: bug, level 1, gssoc25

#806 Make email clickable with hover effect on Privacy page
  Client/src/pages/PrivacyPolicy.jsx
Labels: level 2, gssoc25

#814 Updated idea behind section
  Client/src/components/about/IdeaBehind.jsx
Labels: level 1, gssoc25

#822 Feature : Add emoji option in the chat
  Client/package-lock.json
  Client/package.json
  Client/src/components/chats/chatwindow.tsx
Labels: level 2, gssoc25

#835 Fix: Prevent server crash when Email field is missing in user documents
  Server/Middlewares/usernameHandler.js
  Server/index.js
Labels: level 3, gssoc25

#836 Fix the issues in search functionality of chat
  Client/src/api/userApi.js
  Client/src/components/chats/userlist.tsx
  Client/src/pages/Chats.jsx
  Client/src/queries/userQueries.js
  Server/Controller/UserController.js
  Server/Routes/UserRoutes.js
Labels: level 2, gssoc25

#849 FIX: update the UI of sidebar in friends and settings page
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/settings/Sidebar.jsx
Labels: level 2, gssoc25

#840 Fix current and max streak of user.
  Server/Controller/StudySessionController.js
  Server/Controller/UserController.js
  Server/utils/streakUpdater.js
Labels: bug, level 3, gssoc25

#855 Bcrypt-removed
  Server/Controller/AuthController.js
Labels: level 3, gssoc25

#857 feat: Implement Private study rooms
  Client/package-lock.json
  Client/package.json
  Client/src/components/session/CreateRoomModal.jsx
  Client/src/components/session/RoomCard.jsx
  Client/src/components/session/YourRooms.jsx
  Server/Controller/SessionRoomController.js
  Server/Model/SessionModel.js
  Server/Routes/SessionRoomRoutes.js
  Server/index.js
Labels: level 3, gssoc25

#794 Refactor StudySessionController.js for Maintainability and Performance
  Server/Controller/StudySessionController.js
  Server/Controller/UserController.js
Labels: bug, level 3, gssoc25

#864 Update Friends.jsx #843
  Client/src/components/settings/Friends.jsx
Labels: level 1, gssoc25

#871 Show username in the userProfile card issue-810
  Client/src/components/stats/ProfileCard/ProfileCard.jsx
Labels: level 2, gssoc25

#873 Display username in friend list popup
  Client/src/components/stats/ProfileCard/FriendsPopup.jsx
  Server/Controller/FriendsController.js
Labels: level 2, gssoc25
