Repository EduHaven/EduHaven, pull requests merged in 2025-08, with the labels that each got.

#318 feat: Add NoteNest feature
  Client/index.html
  Client/package-lock.json
  Client/package.json
  Client/src/App.jsx
  Client/src/components/Sidebar.jsx
  Client/src/pages/NoteNest.jsx
Labels: level 3, gssoc25

#332 Privacy policy added
  Client/src/components/settings/Account.jsx
  Client/src/pages/ProjectInfo.jsx
  Server/Controller/UserController.js
  Server/Routes/UserRoutes.js
  Server/package-lock.json
  Server/package.json
Labels: level 1, gssoc25

#335 fixed navbar issue
  Client/src/components/games/2048/Game2048.jsx
  Client/src/components/games/2048/Game2048.module.css
Labels: level 2, gssoc25

#345 fixed issue in stats page
  Client/src/components/stats/Goals.jsx
Labels: level 3, gssoc25

#348 impove the code structure and readability of goalsandnotes
  Client/src/components/home/goals/DeadlinePickerModal.jsx
  Client/src/components/home/goals/GoalsComponent.jsx
  Client/src/components/home/goals/ReactCustomCalendar.css
  Client/src/components/home/goals/SetGoals.jsx
  Client/src/components/home/goals/SetGoals.module.css
  Client/src/components/home/notes/NotesComponent.jsx
  Client/src/pages/Home.jsx
Labels: level 1

#374 fix the time count in leaderboard
  Client/src/components/stats/Leaderboard.jsx
Labels: level 1, gssoc25

#373 fix: search box text color is now visible in all themes
  Client/src/components/session/OtherRooms.jsx
Labels: level 1, gssoc25

#372 [FIX]: #365 Swap the position of games and friends button
  Client/src/components/Sidebar.jsx
Labels: level 1, gssoc25

#391 Refactor Promise .then to await in ConnectDB Class
  Server/Database/Db.js
Labels: level 1, gssoc25

#402 [FIX]: #399 UI & Text Visibility in Notes Section
  Client/src/components/home/notes/NotesComponent.jsx
Labels: level 1, gssoc25

#421 clear buttons clears the skill/interests
  Client/src/components/settings/EducationAndSkills.jsx
Labels: level 2, gssoc25

#422 fix: #410 prevent icons from shrinking in profile card
  Client/src/components/stats/ProfileCard.jsx
Labels: level 1, gssoc25

#425 fix: update error codes to 500, add input validation with toasts, fix fetch typo, and add headers for delete/save events
  Client/src/components/home/calenderComponent/AllEventsPopup.jsx
  Client/src/components/home/calenderComponent/eventPopup.jsx
  Server/Controller/EventController.js
  Server/Middlewares/authMiddleware.js
Labels: level 3, gssoc25

#429 [FIX]: #406 UI of Sudoku game
  Client/src/components/games/sudoku/Sudoku.jsx
  Client/src/components/games/sudoku/Sudoku.module.css
Labels: level 2, gssoc25

#433 Add Enter key functionality to add skills and interests
  Client/src/components/settings/EducationAndSkills.jsx
Labels: level 1, gssoc25

#444 Fix Stats Component: Properly Display Current & Max Streak + Improve Data Mapping
  Client/src/components/stats/StudyStats.jsx
  Client/src/pages/Stats.jsx
  Server/Controller/UserController.js
  Server/Routes/EventRoutes.js
  Server/utils/streakUpdater.js
Labels: level 3, gssoc25

#452 fix syntax error
  Client/src/components/stats/ProfileCard.jsx
  Server/Controller/UserController.js
Labels: level 2, gssoc25

#473 UPDATE: enhance the UI of friends page. #466
  Client/public/profilePic.avif
  Client/src/components/friendsPage/MainContent.jsx
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/friendsPage/UserCard.jsx
  Client/src/pages/FriendsPage.jsx
Labels: level 3, gssoc25

#490 Refactor to manage active tabs
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/settings/Sidebar.jsx
  Client/src/pages/FriendsPage.jsx
  Client/src/pages/Settings.jsx
Labels: level 1, gssoc25

#495 added rotation and transition
  Client/src/components/home/goals/GoalsComponent.jsx
Labels: level 2, gssoc25

#462 #341 Fixed FIX: Button component in our project.
  Client/src/Auth/Auth.jsx
  Client/src/Auth/Login.jsx
  Client/src/Auth/SignUp.jsx
  Client/src/Auth/Verifyotp.jsx
  Client/src/components/ConfirmLogoutModal.jsx
  Client/src/components/CropModal.jsx
  Client/src/components/NotLogedInPage.jsx
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/friendsPage/UserCard.jsx
  Client/src/components/friendsSection/FriendsRequests.jsx
  Client/src/components/friendsSection/SentRequests.jsx
  Client/src/components/friendsSection/SuggestedFriends.jsx
  Client/src/components/games/2048/Game2048.jsx
  Client/src/components/games/Snake/SnakeGame.jsx
  Client/src/components/games/space-type/SpaceType.jsx
  Client/src/components/games/sudoku/Sudoku.jsx
  Client/src/components/games/sudoku/components/Cell.jsx
  Client/src/components/games/tic-tac-toe/TicTacToe.jsx
  Client/src/components/games/whac-a-mole/Whacamole.jsx
  Client/src/components/home/calenderComponent/AllEventsPopup.jsx
  Client/src/components/home/calenderComponent/CalendarComponent.jsx
  Client/src/components/home/calenderComponent/eventPopup.jsx
  Client/src/components/home/goals/DeadlinePickerModal.jsx
  Client/src/components/home/goals/GoalsComponent.jsx
  Client/src/components/home/navBar/AiChatbot.jsx
  Client/src/components/home/navBar/PinnedLinks.jsx
  Client/src/components/home/notes/NotesComponent.jsx
  Client/src/components/home/timerComponent/StatsSummary.jsx
  Client/src/components/home/timerComponent/TimerComponent.jsx
  Client/src/components/landingPage/CTASection.jsx
  Client/src/components/session/CreateRoomModal.jsx
  Client/src/components/session/OtherRooms.jsx
  Client/src/components/session/RoomCard.jsx
  Client/src/components/session/YourRooms.jsx
  Client/src/components/sessionRooms/ChatPannel.jsx
  Client/src/components/sessionRooms/Controls.jsx
  Client/src/components/sessionRooms/InfoPannel.jsx
  Client/src/components/settings/Account.jsx
  Client/src/components/settings/BasicInfo.jsx
  Client/src/components/settings/Delete.jsx
  Client/src/components/settings/EducationAndSkills.jsx
  Client/src/components/settings/Friends.jsx
  Client/src/components/settings/Sidebar.jsx
  Client/src/components/settings/Themes.jsx
  Client/src/components/stats/Goals.jsx
  Client/src/components/stats/Leaderboard.jsx
  Client/src/components/stats/ProfileCard.jsx
  Client/src/components/stats/StudyStats.jsx
  Client/src/components/stats/Test.jsx
  Client/src/components/ui/button.jsx
  Client/src/pages/NoteNest.jsx
Labels: level 3

#498 Added Responsiveness
  Client/src/components/NotLogedInPage.jsx
  Client/src/components/gameRoomComponents/GameRoom.jsx
  Client/src/components/landingPage/CTASection.jsx
  Client/src/components/landingPage/GoalsAndEvents.jsx
  Client/src/components/landingPage/HeroSection.jsx
  Client/src/components/landingPage/MakeFriends.jsx
  Client/src/components/landingPage/NavBar.jsx
  Client/src/components/landingPage/StudyRoom.jsx
  Client/src/pages/NoteNest.jsx
Labels: level 2, gssoc25

#515 Add optimistic updates for todo actions with toast notifications
  Client/src/components/home/goals/GoalsComponent.jsx
Labels: level 2, gssoc25

#521 fix: Decline button doesn't work on friend requests #511
  Client/src/components/friendsSection/FriendsRequests.jsx
Labels: level 2, gssoc25

#532 Removed Skeleton on No pending frd Requests
  Client/src/components/friendsSection/FriendsRequests.jsx
  Client/src/components/friendsSection/SentRequests.jsx
Labels: level 2, gssoc25

#539 Fix user data retrieval
  Client/src/components/stats/ProfileCard.jsx
  Server/Controller/UserController.js
Labels: level 2, gssoc25

#555 Enhance MonthlyLevel component with stats fetching and display new badge SVGs
  Client/public/EduhavenBadges/bronzeBadge.svg
  Client/public/EduhavenBadges/diamondBadge.svg
  Client/public/EduhavenBadges/emeraldBadge.svg
  Client/public/EduhavenBadges/goldBadge.svg
  Client/public/EduhavenBadges/platinumBadge.svg
  Client/public/EduhavenBadges/silverBadge.svg
  Client/src/components/stats/MonthlyLevel.jsx
Labels: level 3, gssoc25

#556 add animated popup and improved friend list display
  Client/src/components/stats/ProfileCard.jsx
Labels: level 2, gssoc25

#567 Add profile completion checks and notifications in settings and home components
  Client/src/components/settings/BasicInfo.jsx
  Client/src/components/settings/EducationAndSkills.jsx
  Client/src/components/settings/Sidebar.jsx
  Client/src/contexts/UserProfileContext.jsx
  Client/src/pages/Home.jsx
Labels: level 3, gssoc25

#578 fix the blob thing
  Client/src/components/stats/ProfileCard/ProfileCard.jsx
Labels: level 1, gssoc25

#582 Created Chat page
  Client/package-lock.json
  Client/src/App.jsx
  Client/src/components/Sidebar.jsx
  Client/src/components/chats/chatwindow.tsx
  Client/src/components/chats/userlist.tsx
  Client/src/pages/Chats.jsx
Labels: level 3, gssoc25
