Repository EduHaven/EduHaven, pull requests merged in 2025-10, with the labels that each got.

#885 fix slogan text issue
  Client/src/components/home/navBar/Slogan.jsx
Labels: level 1, gssoc25

#886 fix popup width
  Client/src/components/ui/Popup.jsx
Labels: level 1, gssoc25

#889 Stats: refine auth/loading handling and add loading skeletons
  Client/src/components/AdCard.jsx
  Client/src/components/stats/Leaderboard.jsx
  Client/src/components/stats/MonthlyLevel.jsx
  Client/src/components/stats/StudyStats.jsx
  Client/src/pages/Stats.jsx
Labels: level 2, gssoc25

#891 fixed join session bug
  Client/src/components/session/CreateRoomModal.jsx
  Client/src/components/session/RoomCard.jsx
  Server/Controller/SessionRoomController.js
  Server/Routes/SessionRoomRoutes.js
Labels: level 3, gssoc25

#890 Fixed google oauth btn frontend
  Client/src/Auth/Login.jsx
  Client/src/Auth/SignUp.jsx
Labels: level 1, gssoc25

#893 add search functionality and infinite scroll
  Client/src/api/friendApi.js
  Client/src/components/friendsPage/MainContent.jsx
  Client/src/components/friendsPage/TabNavigation.jsx
  Client/src/components/friendsPage/UserCard.jsx
  Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
  Client/src/pages/FriendsPage.jsx
  Client/src/queries/friendQueries.js
  Server/Controller/FriendsController.js
Labels: level 3, gssoc25

#912 Fix: Logo Overlap and Layout Alignment on About Page
  Client/src/components/about/Hero.jsx
Labels: level 2, gssoc25

#913 add color support
  Client/src/components/home/notes/BottomControls.jsx
  Client/src/components/home/notes/NotesComponent.jsx
Labels: level 3, gssoc25
